// GxEPD2_reTerminal_E1002_Image.ino
//
// Display a 6-color photo on the Seeed Studio reTerminal E1002
//   - 7.3" 6-Color ePaper, 800 x 480 pixels
//   - Panel: GDEP073E01 (ED2208 controller, 6-color ACeP — no orange!)
//   - Host MCU: ESP32-S3 (XIAO ESP32-S3)
//   - Supported colors: Black, White, Red, Green, Blue, Yellow
//
// Required Arduino settings (Tools menu):
//   Board:  XIAO_ESP32S3
//
// Pin mapping (from Seeed Setup521):
//   SCK=7, MOSI=9, CS=10, DC=11, RST=12, BUSY=13
//   No MISO needed, no special enable pins.
//
// Image header generation:
//   Run convert_image.py (located in this sketch directory) on any JPEG.
//   It produces a mocha800x480.h (or custom-named) PROGMEM array ready for
//   drawNative().  Each pixel is stored as a 4-bit nibble (2 pixels/byte):
//     0x0 = Black   0x1 = White   0x2 = Green
//     0x3 = Blue    0x4 = Red     0x5 = Yellow
//
// Usage:
//   1. Place your image header (e.g. mocha800x480.h) in this sketch folder.
//   2. Update the #include below and the IMAGE_* constants.
//   3. Upload and let the panel refresh (~25-30 s).

#include <SPI.h>
#include <GxEPD2_7C.h>
#include "mocha800x480.h"   // <-- generated by convert_image.py

// ===== Pin mapping =====
#define EPD_SCK_PIN   7
#define EPD_MOSI_PIN  9
#define EPD_CS_PIN    10
#define EPD_DC_PIN    11
#define EPD_RES_PIN   12
#define EPD_BUSY_PIN  13

SPIClass hspi(HSPI);

// ===== Display: 7.3" 6-Color 800x480 =====
// MAX_DISPLAY_BUFFER_SIZE caps page-buffer RAM usage.  16 kB is safe on
// the XIAO ESP32-S3 (512 kB SRAM).  Each byte holds 2 pixels (4 bits each).
#define MAX_DISPLAY_BUFFER_SIZE 16000u
#define MAX_HEIGHT(EPD) \
    (EPD::HEIGHT <= (MAX_DISPLAY_BUFFER_SIZE) / (EPD::WIDTH / 2) \
         ? EPD::HEIGHT \
         : (MAX_DISPLAY_BUFFER_SIZE) / (EPD::WIDTH / 2))

GxEPD2_7C<GxEPD2_730c_GDEP073E01, MAX_HEIGHT(GxEPD2_730c_GDEP073E01)>
    display(GxEPD2_730c_GDEP073E01(EPD_CS_PIN, EPD_DC_PIN, EPD_RES_PIN, EPD_BUSY_PIN));

// ===== Image metadata (must match the values in the generated header) =====
// The generated header exposes one constant array:  image800x480[]
// Width / height must match the actual pixel dimensions in the header.
#define IMAGE_WIDTH   800
#define IMAGE_HEIGHT  480

void setup()
{
  Serial.begin(115200);
  delay(200);
  Serial.println(F("[E1002] GxEPD2 reTerminal E1002 — Image Demo"));

  pinMode(EPD_RES_PIN, OUTPUT);
  pinMode(EPD_DC_PIN,  OUTPUT);
  pinMode(EPD_CS_PIN,  OUTPUT);

  // Use HSPI with no MISO (pass -1).  2 MHz is conservative; increase to
  // 4 MHz only if your cable is short and signal quality is good.
  hspi.begin(EPD_SCK_PIN, /*MISO=*/-1, EPD_MOSI_PIN, /*SS=*/-1);
  display.epd2.selectSPI(hspi, SPISettings(2000000, MSBFIRST, SPI_MODE0));

  display.init(0);

  Serial.print(F("[E1002] Panel: "));
  Serial.print(display.width());
  Serial.print('x');
  Serial.println(display.height());

  drawImage();

  Serial.println(F("[E1002] Done. Hibernating."));
  display.hibernate();
}

void loop() {}

// ---------------------------------------------------------------------------
// drawImage
//   Renders image800x480[] (or whatever your header exports) using drawNative.
//   drawNative expects:
//     - data pointer into PROGMEM
//     - x, y   : top-left corner on the panel
//     - w, h   : image width / height in pixels
//     - invert : false (our nibble encoding is already native)
//     - mirror_y: false
//     - pgm     : true (data is in PROGMEM)
//
//   The library pages through the image automatically when the buffer is
//   smaller than the full frame.
// ---------------------------------------------------------------------------
void drawImage()
{
  Serial.println(F("[E1002] drawImage: starting full-panel render"));

  display.setFullWindow();
  display.drawNative(
    image800x480,     // PROGMEM array from mocha800x480.h
    0,                // x offset (0 = left edge)
    0,                // y offset (0 = top edge)
    0,                // no sub-image x offset
    IMAGE_WIDTH,      // pixel width
    IMAGE_HEIGHT,     // pixel height
    false,            // invert: keep native nibble values
    false,            // mirror_y: no vertical flip
    true              // pgm: data is in PROGMEM
  );

  Serial.println(F("[E1002] drawImage: done"));
}
